### ISSUE TITLE
Attribute Error When Running

### ISSUE THREAD

**Issue by MatthewT1** [alex-phillips/plex-autocollections#8]
I've installed all the requirements and am using Python 3.4, but I'm getting this when I try to run main.py: 

``PS C:\users\gamingRig\plex-autocollections\plex-autocollections> python.exe .\main.py
Plex Username: matthew.kt
Password:
Traceback (most recent call last):
  File ".\main.py", line 66, in <module>
    plex = Plex()
  File ".\main.py", line 10, in __init__
    self.account = self.get_account()
  File "<decorator-gen-2>", line 2, in get_account
  File "C:\Python34\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Python34\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File ".\main.py", line 20, in get_account
    return MyPlexAccount(username, password)
  File "C:\Python34\lib\site-packages\plexapi\myplex.py", line 20, in __init__
    self.authenticationToken = data.attrib.get('authenticationToken')
AttributeError: 'str' object has no attribute 'attrib'
PS C:\users\gamingRig\plex-autocollections\plex-autocollections>``

Any idea what I should try to get it running?

**Comment by MatthewT1** [comment]
Disregard, had to upgrade Python to 3.6 - works great!
